### ISSUE TITLE
Oversized regions dropped in remapped chromosomes

### ISSUE THREAD

**Issue by Lipastomies** [FINNGEN/finemapping-pipeline#55]
Bug: If a chromosome that has been remapped (e.g. chromosome 23 to chromosome X) contains regions that are larger than the size threshold, they are filtered with the original chromosome name, leading in those regions being dropped from the results.

The bug seems to be due to the region beds being in the original chromosome mapping, and the summary statistics that the regions are built from being in the mapped chromosome. When the summstats are filtered using the original chromosome beds, the chromosomes do not match, which filters the whole region out.

This was seen in R9, where M13_ARTHROSIS_KNEE misses the complete chrX:95-105MB region, even though there is signal (https://r9.finngen.fi/pheno/M13_ARTHROSIS_KNEE).

@mkanai @Fedja what do you think, what would be the best way to fix this? We could
- remap also the beds, but then they'll be in a different chromosome than before (intentional or not?)
- not remap in the region selection, and remap the chromosomes using e.g. sed after region selection
- Something else?

**Comment by Lipastomies** [comment]
Here are all the missing regions for R9:
```
endpoint                          chr start      end        length
BMI                               23  61367886   69163705   7795819
BMI                               23  69263873   71693873   2430000
HEIGHT                            23  70648705   73437826   2789121
HEIGHT                            23  73480358   88034950   14554592
HEIGHT                            23  88281177   90711177   2430000
HEIGHT_IRN                        23  100754204  110351792  9597588
HEIGHT_IRN                        23  110545517  112316987  1771470
HEIGHT_IRN                        23  112837706  115267706  2430000
HEIGHT_IRN                        23  128810328  136043838  7233510
HEIGHT_IRN                        23  136152608  141459179  5306571
HEIGHT_IRN                        23  68065696   70252696   2187000
HEIGHT_IRN                        23  70669734   73437826   2768092
HEIGHT_IRN                        23  73480358   90381912   16901554
M13_ARTHROSIS                     23  101430143  108289067  6858924
M13_ARTHROSIS                     23  97149228   101382560  4233332
M13_ARTHROSIS_INCLAVO             23  103103461  107824802  4721341
M13_ARTHROSIS_INCLAVO             23  97015966   102985947  5969981
M13_ARTHROSIS_KNEE                23  101430143  108289067  6858924
M13_ARTHROSIS_KNEE                23  97149228   101382560  4233332
M13_ARTHROSIS_KNEE_PRIM_KNEESURG  23  101384225  108289067  6904842
M13_ARTHROSIS_KNEE_PRIM_KNEESURG  23  108459531  111159531  2700000
M13_ARTHROSIS_KNEE_PRIM_KNEESURG  23  97149228   101382560  4233332
PRIM_KNEEARTHROSIS                23  104197527  108154067  3956540
PRIM_KNEEARTHROSIS                23  108459531  111159531  2700000
PRIM_KNEEARTHROSIS                23  96006033   103995143  7989110
WEIGHT                            23  67322284   75422992   8100708
WEIGHT                            23  75455516   83739802   8284286
WEIGHT_IRN                        23  67322284   73637105   6314821
WEIGHT_IRN                        23  73820426   80495696   6675270
```

**Comment by mkanai** [comment]
Great catch @Lipastomies! I think it's essentially `filter_sumstats` bug which does not map chromosomes to integers
https://github.com/FINNGEN/finemapping-pipeline/blob/b54125e79d0085d33632dcad93cf19849197f276/python/make_finemap_inputs.py#L148-L151

while `generate_bed` does.
https://github.com/FINNGEN/finemapping-pipeline/blob/b54125e79d0085d33632dcad93cf19849197f276/python/make_finemap_inputs.py#L196-L197

So, the most straightforward fix would be just replacing `(df.chromosome == f.chrom)` with `(df.chromosome.map(CHROM_MAPPING_INT) == f.chrom)` in L150.

Bigger question might be whether we want to keep integer chromosomes in a bed file... I don't remember why I forced so (maybe pybedtools restrictions?), but am generally fine to introduce a breaking change so that we can make it consistent with sumstats. In this case, I think the fix would be simply removing `CHROM_MAPPING_INT` mapping from L197.

@Lipastomies Do you mind investigating whether this change works and would affect any other subsequent pipelines that perhaps use .bed files?

Thanks!

**Comment by Lipastomies** [comment]
I don't think we use them anywhere. The beds are not used later in the pipeline, and I'm not aware of any other pipelines using them.
